# Generated by Django 3.1.1 on 2021-01-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_enrolledstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledstudent',
            name='OrderId',
        ),
        migrations.RemoveField(
            model_name='enrolledstudent',
            name='Signature',
        ),
        migrations.RemoveField(
            model_name='enrolledstudent',
            name='TimeStamp',
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='screenShot',
            field=models.URLField(default='NA'),
        ),
        migrations.AddField(
            model_name='student',
            name='profilePicture',
            field=models.URLField(default='NA'),
        ),
    ]
