# Generated by Django 3.1.1 on 2021-01-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210129_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledstudent',
            name='paymentType',
            field=models.CharField(default='Net Banking', max_length=100),
        ),
    ]
