# Generated by Django 3.1.1 on 2021-01-30 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_enrolledstudent_paymenttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledstudent',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='enrolledstudent',
            old_name='PaymentId',
            new_name='paymentId',
        ),
    ]
