# Generated by Django 3.1.5 on 2021-01-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20210130_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledstudent',
            old_name='paymentId',
            new_name='paymentID',
        ),
        migrations.AlterField(
            model_name='student',
            name='profilePicture',
            field=models.FileField(default='NA', upload_to=''),
        ),
    ]
