# Generated by Django 3.1.5 on 2021-01-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20210130_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstudent',
            name='screenShot',
            field=models.ImageField(default='NA', upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='profilePicture',
            field=models.ImageField(default='NA', upload_to=''),
        ),
    ]
