# Generated by Django 3.1.1 on 2021-02-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20210131_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstudent',
            name='screenShot',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='profilePicture',
            field=models.CharField(max_length=500),
        ),
    ]
