# Generated by Django 3.1.1 on 2021-02-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20210201_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(default='1234567890', max_length=15),
        ),
    ]
